### ISSUE TITLE
Add functions for swiping up and down to include all swipe directions

### ISSUE THREAD

**Issue by jaredmharris** [alexandre-garrec/react-swipe-card#2]
Where would one start if they wanted to add functions for swiping up and down?

**Comment by alexandre-garrec** [comment]
I made a PR, can it solve your problem?

**Comment by jaredmharris** [comment]
This looks good. Is it possible to update the story so people can see the functionality on your demo site?

**Comment by alexandre-garrec** [comment]
Demo and package is up to date

https://alexandre-garrec.github.io/react-swipe-card/?selectedKind=Tinder%20card&selectedStory=all%20swipe%20directions&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel
