### ISSUE TITLE
Warning: Each child in an array should have a unique "key" prop.

### ISSUE THREAD

**Issue by zdenham** [alexandre-garrec/react-swipe-card#5]
The node module with the demo code kept throwing this warning. 
Was able to quiet it by changing line 132 in Cards.js (in node_module) to:

{ className: (_this3.state['alert' + d] ? 'alert-visible' : '') + ' alert-' + d.toLowerCase() + ' alert', **key : d** },

just adding the key: <unique_key> did the trick, but I'm not sure if thats a permanent fix

**Comment by alexandre-garrec** [comment]
It's done !
